registry:
    class: lymph.discovery.zookeeper:ZookeeperServiceRegistry
    zkclient: dep:kazoo


event_system:
    class: lymph.events.kombu:KombuEventSystem
    transport: amqp
    hostname: rabbitmq  # you may want to change me


dependencies:
    kazoo:
        class: kazoo.client:KazooClient
        hosts: zk  # you may want to change me
 
 
instances:
    sentiment_client:
        command: lymph instance --config=sentiment_client.yml --reload
